before_cache:
    - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
    - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
    yarn: true
    directories:
        - $HOME/.gradle/caches/
        - $HOME/.gradle/wrapper/
jobs:
    include:
      - stage: Build
        name: "Java"
        language: java
        jdk: openjdk8
        install: skip
        script: ./gradlew -Pprod compileJava
      - stage: Build
        name: "TypeScript"
        language: node_js
        node_js: 12.3.1
        install: yarn install
        script: yarn build
      - stage: Test
        name: "Java"
        language: java
        jdk: openjdk8
        install: skip
        script: ./gradlew executeTests
      - stage: Test
        name: "TypeScript"
        language: node_js
        node_js: 12.3.1
        install: yarn install
        script: yarn test
      - stage: Lint
        name: "Java"
        language: java
        jdk: openjdk8
        install: skip
        script: ./gradlew spotlessCheck
      - stage: Lint
        name: "TypeScript"
        language: node_js
        node_js: 12.3.1
        install: yarn install
        script: yarn prettier:check
