version: '2.4'
services:
    artemis-app:
        image: ghcr.io/ls1intum/artemis-service:${TAG:-latest}
        volumes:
            - ${PWD}/config/application-artemis.yml:/home/artemis/application-artemis.yml:ro
        environment:
            - SPRING_PROFILES_ACTIVE=prod,artemis,openapi,jira,bamboo,bitbucket,scheduling
            - SPRING_CLOUD_CONFIG_NAME=artemis
            - SERVER_PORT=8080
            # common environment variables
            - SPRING_DEVTOOLS_RESTART_ENABLED=true
            - SPRING_DEVTOOLS_LIVERELOAD_ENABLED=false
            - SPRING_DATASOURCE_TYPE=com.zaxxer.hikari.HikariDataSource
            - SPRING_DATASOURCE_USERNAME=root
            - SPRING_DATASOURCE_HIKARI_POOLNAME=Hikari
            - SPRING_DATASOURCE_HIKARI_AUTO_COMMIT=false
            - SPRING_DATASOURCE_HIKARI_DATA_SOURCE_PROPERTIES_CACHEPREPSTMTS=true
            - SPRING_DATASOURCE_HIKARI_DATA_SOURCE_PROPERTIES_PREPSTMTCACHESIZE=250
            - SPRING_DATASOURCE_HIKARI_DATA_SOURCE_PROPERTIES_PREPSTMTCACHESQLLIMIT=2048
            - SPRING_DATASOURCE_HIKARI_DATA_SOURCE_PROPERTIES_USESERVERPREPSTMTS=true
            - SPRING_JPA_DATABASE_PLATFORM=org.hibernate.dialect.MySQL8Dialect
            - SPRING_JPA_DATABASE=MYSQL
            - SPRING_JPA_SHOW_SQL=false
            - SPRING_LIQUIBASE_CONTEXTS=prod
            - SPRING_THYMELEAF_CACHE=true
            - SPRING_CLOUD_CONFIG_FAILFAST=true
            - SPRING_CLOUD_CONFIG_PROFILE=prod
            - SPRING_CLOUD_CONFIG_LABEL=main
            - SPRING_CLOUD_CONFIG_ENABLED=false
            - SPRING_MESSAGES_CACHEDURATION=PT1S
            - SPRING_SLEUTH_SAMPLER_PROBABILITY=1
            - JHIPSTER_SECURITY_AUTHENTICATION_JWT_BASE64_SECRET=bXktc2VjcmV0LWtleS13aGljaC1zaG91bGQtYmUtY2hhbmdlZC1pbi1wcm9kdWN0aW9uLWFuZC1iZS1iYXNlNjQtZW5jb2RlZAo=
            - JHIPSTER_SECURITY_AUTHENTICATION_JWT_TOKEN_VALIDITY_IN_SECONDS=86400
            - JHIPSTER_SECURITY_AUTHENTICATION_JWT_TOKEN_VALIDITY_IN_SECONDS_FOR_REMEMBER_ME=2592000
            - JHIPSTER_LOGGING_LOGSTASH_ENABLED=false
            - JHIPSTER_LOGGING_AUDIT_EVENTS_RETENTION_PERIOD=120
            - SERVER_COMPRESSION_ENABLED=true
            - SERVER_COMPRESSION_MIMETYPES=text/html,text/xml,text/plain,text/css, application/javascript, application/json
            - SERVER_COMPRESSION_MINRESPONSESIZE=1024
            - SERVER_URL=https://localhost:8080
        expose:
            - "8080"
        networks:
            - artemis
        depends_on:
            - artemis-mysql
            - jhipster-registry

    usermanagement-app:
        image: ghcr.io/ls1intum/artemis-usermanagement-service:${TAG:-latest}
        volumes:
            - ${PWD}/config/application-artemis.yml:/home/artemis/user-management/application-artemis.yml:ro
        environment:
            - SPRING_PROFILES_ACTIVE=prod,artemis,jira,scheduling
            - SPRING_CLOUD_CONFIG_NAME=userManagement
            - SERVER_PORT=8087
            # common environment variables
            - SPRING_DEVTOOLS_RESTART_ENABLED=true
            - SPRING_DEVTOOLS_LIVERELOAD_ENABLED=false
            - SPRING_DATASOURCE_TYPE=com.zaxxer.hikari.HikariDataSource
            - SPRING_DATASOURCE_USERNAME=root
            - SPRING_DATASOURCE_HIKARI_POOLNAME=Hikari
            - SPRING_DATASOURCE_HIKARI_AUTO_COMMIT=false
            - SPRING_DATASOURCE_HIKARI_DATA_SOURCE_PROPERTIES_CACHEPREPSTMTS=true
            - SPRING_DATASOURCE_HIKARI_DATA_SOURCE_PROPERTIES_PREPSTMTCACHESIZE=250
            - SPRING_DATASOURCE_HIKARI_DATA_SOURCE_PROPERTIES_PREPSTMTCACHESQLLIMIT=2048
            - SPRING_DATASOURCE_HIKARI_DATA_SOURCE_PROPERTIES_USESERVERPREPSTMTS=true
            - SPRING_JPA_DATABASE_PLATFORM=org.hibernate.dialect.MySQL8Dialect
            - SPRING_JPA_DATABASE=MYSQL
            - SPRING_JPA_SHOW_SQL=false
            - SPRING_LIQUIBASE_CONTEXTS=prod
            - SPRING_THYMELEAF_CACHE=true
            - SPRING_CLOUD_CONFIG_FAILFAST=true
            - SPRING_CLOUD_CONFIG_PROFILE=prod
            - SPRING_CLOUD_CONFIG_LABEL=main
            - SPRING_CLOUD_CONFIG_ENABLED=false
            - SPRING_MESSAGES_CACHEDURATION=PT1S
            - SPRING_SLEUTH_SAMPLER_PROBABILITY=1
            - JHIPSTER_SECURITY_AUTHENTICATION_JWT_BASE64_SECRET=bXktc2VjcmV0LWtleS13aGljaC1zaG91bGQtYmUtY2hhbmdlZC1pbi1wcm9kdWN0aW9uLWFuZC1iZS1iYXNlNjQtZW5jb2RlZAo=
            - JHIPSTER_SECURITY_AUTHENTICATION_JWT_TOKEN_VALIDITY_IN_SECONDS=86400
            - JHIPSTER_SECURITY_AUTHENTICATION_JWT_TOKEN_VALIDITY_IN_SECONDS_FOR_REMEMBER_ME=2592000
            - JHIPSTER_LOGGING_LOGSTASH_ENABLED=false
            - JHIPSTER_LOGGING_AUDIT_EVENTS_RETENTION_PERIOD=120
            - SERVER_COMPRESSION_ENABLED=true
            - SERVER_COMPRESSION_MIMETYPES=text/html,text/xml,text/plain,text/css, application/javascript, application/json
            - SERVER_COMPRESSION_MINRESPONSESIZE=1024
        expose:
            - "8087"
        networks:
            - artemis
        depends_on:
            - artemis-mysql
            - jhipster-registry

    lecture-app:
        image: ghcr.io/ls1intum/artemis-lecture-service:${TAG:-latest}
        volumes:
            - ${PWD}/config/application-artemis.yml:/home/artemis/lecture/application-artemis.yml:ro
        environment:
            - SPRING_PROFILES_ACTIVE=prod,artemis
            - SPRING_CLOUD_CONFIG_NAME=lecture
            - SERVER_PORT=8086
            # common environment variables
            - SPRING_DEVTOOLS_RESTART_ENABLED=true
            - SPRING_DEVTOOLS_LIVERELOAD_ENABLED=false
            - SPRING_DATASOURCE_TYPE=com.zaxxer.hikari.HikariDataSource
            - SPRING_DATASOURCE_USERNAME=root
            - SPRING_DATASOURCE_HIKARI_POOLNAME=Hikari
            - SPRING_DATASOURCE_HIKARI_AUTO_COMMIT=false
            - SPRING_DATASOURCE_HIKARI_DATA_SOURCE_PROPERTIES_CACHEPREPSTMTS=true
            - SPRING_DATASOURCE_HIKARI_DATA_SOURCE_PROPERTIES_PREPSTMTCACHESIZE=250
            - SPRING_DATASOURCE_HIKARI_DATA_SOURCE_PROPERTIES_PREPSTMTCACHESQLLIMIT=2048
            - SPRING_DATASOURCE_HIKARI_DATA_SOURCE_PROPERTIES_USESERVERPREPSTMTS=true
            - SPRING_JPA_DATABASE_PLATFORM=org.hibernate.dialect.MySQL8Dialect
            - SPRING_JPA_DATABASE=MYSQL
            - SPRING_JPA_SHOW_SQL=false
            - SPRING_LIQUIBASE_CONTEXTS=prod
            - SPRING_THYMELEAF_CACHE=true
            - SPRING_CLOUD_CONFIG_FAILFAST=true
            - SPRING_CLOUD_CONFIG_PROFILE=prod
            - SPRING_CLOUD_CONFIG_LABEL=main
            - SPRING_CLOUD_CONFIG_ENABLED=false
            - SPRING_MESSAGES_CACHEDURATION=PT1S
            - SPRING_SLEUTH_SAMPLER_PROBABILITY=1
            - JHIPSTER_SECURITY_AUTHENTICATION_JWT_BASE64_SECRET=bXktc2VjcmV0LWtleS13aGljaC1zaG91bGQtYmUtY2hhbmdlZC1pbi1wcm9kdWN0aW9uLWFuZC1iZS1iYXNlNjQtZW5jb2RlZAo=
            - JHIPSTER_SECURITY_AUTHENTICATION_JWT_TOKEN_VALIDITY_IN_SECONDS=86400
            - JHIPSTER_SECURITY_AUTHENTICATION_JWT_TOKEN_VALIDITY_IN_SECONDS_FOR_REMEMBER_ME=2592000
            - JHIPSTER_LOGGING_LOGSTASH_ENABLED=false
            - JHIPSTER_LOGGING_AUDIT_EVENTS_RETENTION_PERIOD=120
            - SERVER_COMPRESSION_ENABLED=true
            - SERVER_COMPRESSION_MIMETYPES=text/html,text/xml,text/plain,text/css, application/javascript, application/json
            - SERVER_COMPRESSION_MINRESPONSESIZE=1024
        expose:
            - "8086"
        networks:
            - artemis
        depends_on:
            - artemis-mysql
            - jhipster-registry

    gateway-app:
        image: ghcr.io/ls1intum/artemis-gateway:${TAG:-latest}
        environment:
            - SPRING_PROFILES_ACTIVE=prod
            - SPRING_CLOUD_CONFIG_NAME=gateway
            - SERVER_PORT=8089
            - SPRING_DEVTOOLS_RESTART_ENABLED=true
            - SPRING_DEVTOOLS_LIVERELOAD_ENABLED=false
            - SPRING_THYMELEAF_CACHE=true
            - SPRING_CLOUD_CONFIG_FAILFAST=true
            - SPRING_CLOUD_CONFIG_PROFILE=prod
            - SPRING_CLOUD_CONFIG_LABEL=main
            - SPRING_CLOUD_CONFIG_ENABLED=false
            - SPRING_MESSAGES_CACHEDURATION=PT1S
            - SPRING_SLEUTH_SAMPLER_PROBABILITY=1
            - JHIPSTER_SECURITY_AUTHENTICATION_JWT_BASE64_SECRET=bXktc2VjcmV0LWtleS13aGljaC1zaG91bGQtYmUtY2hhbmdlZC1pbi1wcm9kdWN0aW9uLWFuZC1iZS1iYXNlNjQtZW5jb2RlZAo=
            - JHIPSTER_SECURITY_AUTHENTICATION_JWT_TOKEN_VALIDITY_IN_SECONDS=86400
            - JHIPSTER_SECURITY_AUTHENTICATION_JWT_TOKEN_VALIDITY_IN_SECONDS_FOR_REMEMBER_ME=2592000
            - JHIPSTER_LOGGING_LOGSTASH_ENABLED=false
            - JHIPSTER_LOGGING_AUDIT_EVENTS_RETENTION_PERIOD=120
            - SERVER_COMPRESSION_ENABLED=true
            - SERVER_COMPRESSION_MIMETYPES=text/html,text/xml,text/plain,text/css, application/javascript, application/json
            - SERVER_COMPRESSION_MINRESPONSESIZE=1024
        ports:
            - 8089:8089
        networks:
            - artemis
        depends_on:
            - jhipster-registry

    jhipster-registry:
        image: jhipster/jhipster-registry:v6.8.0
        volumes:
            - ${PWD}/config/registry-config:/central-config
        environment:
            - SPRING_PROFILES_ACTIVE=prod,api-docs
            - SPRING_CLOUD_CONFIG_SERVER_COMPOSITE_0_SEARCH_LOCATIONS=file:./central-config/
        ports:
            - 8761:8761
        networks:
            - artemis

    artemis-mysql:
        image: mysql:8.0.27
        volumes:
            - ./db/:/var/lib/mysql/
        container_name: artemis_mysql
        environment:
            - MYSQL_ALLOW_EMPTY_PASSWORD=yes
            - MYSQL_ROOT_PASSWORD=
            - MYSQL_DATABASE=Artemis
        expose:
            - "3306"
        command: mysqld --lower_case_table_names=1 --skip-ssl --character_set_server=utf8mb4 --collation-server=utf8mb4_unicode_ci --explicit_defaults_for_timestamp
        networks:
            - artemis

    activemq-broker:
        image: vromero/activemq-artemis:latest
        environment:
            - ARTEMIS_USERNAME=guest
            - ARTEMIS_PASSWORD=guest
            - ENABLE_JMX=true
            - JMX_PORT=1199
            - JMX_RMI_PORT=1198
            - ENABLE_JMX_EXPORTER=true
        ports:
            - 8161:8161
        expose:
            - "61616"
        networks:
            - artemis

networks:
    artemis:
        driver: "bridge"
