# ===================================================================
# GitLab specific properties: this file will only be loaded during startup if the profile gitlab is active
#
# This configuration overrides the application.yml file.
# ===================================================================

gitlab:
    # The following (optional) parameter allows to enable the use of pseudonyms.
    # Iff activated, the user's first and last name are not transferred to gitlab.
    # Instead the user will be called "user <loginname>".
    # See also https://gitlab.com/gitlab-org/gitlab/-/issues/14123
    use-pseudonyms: false
