# ===================================================================
# Local VC specific properties: this file will only be loaded during startup if the profile localvc is active
#
# This configuration overrides the application.yml file.
# ===================================================================
artemis:
    version-control:
        # A folder in which the local git repos are stored as bare repositories.
        # Only required when using the profile 'localvc' to save repositories locally instead of on Bitbucket or Gitlab.
        # In a multi node setup, this folder should be in a shared file system area (e.g. based on NFS), so that user can access the same files over multiple nodes.
        local-vcs-repo-path: ./local-vcs-repos
        url: http://localhost:8000
        build-agent-git-username: buildjob_user # Replace with more secure credentials for production. Required for https access to localvc. This config must be set for build agents and localvc.
        build-agent-git-password: buildjob_password # Replace with more secure credentials for production. Required for https access to localvc. This config must be set for build agents and localvc. You can also use an ssh key
        use-version-control-access-token: true
        show-clone-url-without-token: true

