version: '2.1'
services:
    artemis-mysql:
        image: mysql:8.0.27
        # volumes:
        #     - ~/volumes/jhipster/Artemis/mysql/:/var/lib/mysql/
        environment:
            - MYSQL_ALLOW_EMPTY_PASSWORD=yes
            - MYSQL_ROOT_PASSWORD=
            - MYSQL_DATABASE=Artemis
        ports:
            - 3306:3306
        command: mysqld --lower_case_table_names=1 --skip-ssl --character_set_server=utf8mb4 --collation-server=utf8mb4_unicode_ci --explicit_defaults_for_timestamp
        networks:
            - artemis
        healthcheck:
            test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
            timeout: 20s
            retries: 10

networks:
    artemis:
        driver: "bridge"
