apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: artemis-gateway
spec:
  rules:
  - host: artemis-gateway.artemis.rancher.localhost
    http:
      paths:
      - backend:
          service:
            name: gateway
            port:
              number: 8089
        pathType: ImplementationSpecific
  tls:
  - hosts:
    - artemis-gateway.artemis.rancher.localhost
