version: "2"
services:
    gitlab:
        image: gitlab/gitlab-ce:latest
        volumes:
            - artemis-gitlab-data:/var/opt/gitlab
            - artemis-gitlab-logs:/var/log/gitlab
            - artemis-gitlab-config:/etc/gitlab
            - ./gitlab/gitlab-setup.sh:/gitlab-setup.sh
        ports:
            - "2222:22"
            - "8082:80"
        mem_limit: 3000m
        hostname: gitlab
        networks:
            artemis:
                ipv4_address: 172.20.0.4
    jenkins:
        build: jenkins
        volumes:
            - artemis-jenkins-data:/var/jenkins_home
            - /var/run/docker.sock:/var/run/docker.sock
        ports:
            - "8083:8080"
        hostname: jenkins
        networks:
            artemis:
                ipv4_address: 172.20.0.5

networks:
    artemis:
        driver: "bridge"
        ipam:
            driver: default
            config:
                - subnet: 172.20.0.0/24

volumes:
    artemis-gitlab-data:
    artemis-gitlab-logs:
    artemis-gitlab-config:
    artemis-jenkins-data:
