# ----------------------------------------------------------------------------------------------------------------------
# GitLab-Jenkins Setup
# ----------------------------------------------------------------------------------------------------------------------

services:
    gitlab:
        extends:
            file: ./gitlab/gitlab.yml
            service: gitlab
    jenkins:
        extends:
            file: ./jenkins/jenkins.yml
            service: jenkins

networks:
    artemis:
        driver: "bridge"
        name: artemis
volumes:
    artemis-gitlab-data:
        name: artemis-gitlab-data
    artemis-gitlab-logs:
        name: artemis-gitlab-logs
    artemis-gitlab-config:
        name: artemis-gitlab-config
    artemis-jenkins-data:
        name: artemis-jenkins-data
