version: '2'
services:
    artemis-mysql:
        image: mysql:8.0.25
        # volumes:
        #     - ~/volumes/jhipster/Artemis/mysql/:/var/lib/mysql/
        environment:
            - MYSQL_ALLOW_EMPTY_PASSWORD=yes
            - MYSQL_ROOT_PASSWORD=
            - MYSQL_DATABASE=Artemis
        ports:
            - 3306:3306
        command: mysqld --lower_case_table_names=1 --skip-ssl --character_set_server=utf8mb4 --explicit_defaults_for_timestamp
        networks:
            - artemis

networks:
    artemis:
        driver: "nat"
