blank_issues_enabled: false
contact_links:
  - name: â“ Support Question
    url: mailto:artemis.in@tum.de
    about: ğŸ›‘ Please do not file questions or support requests on the GitHub issues tracker. Please contact the Artemis Team using Email.
