blank_issues_enabled: false
contact_links:
  - name: â“ Support Question
    url: https://artemis.ase.in.tum.de/mailto
    about: Please do not file questions or support requests on the GitHub issues tracker. Please contact the Artemis Team using Email at artemis.in@tum.de.
