# ----------------------------------------------------------------------------------------------------------------------
# PostgreSQL base service
# ----------------------------------------------------------------------------------------------------------------------

services:
    postgresql:
        container_name: artemis-postgresql
        image: postgres:15-alpine
        pull_policy: always
        user: postgres
        volumes:
            - artemis-postgresql-data:/var/lib/postgresql/data
        # DO NOT use an empty password and the POSTGRES_HOST_AUTH_METHOD=trust for production systems!
        environment:
            POSTGRES_HOST_AUTH_METHOD: trust
            POSTGRES_USER: postgres
            POSTGRES_DB: Artemis
        ports:
            - "5432:5432"
        healthcheck:
            test: pg_isready -U postgres -d Artemis
            interval: 5s
            timeout: 3s
            retries: 30
            start_period: 30s
        shm_size: '256m'
        networks:
            - artemis

networks:
    artemis:
        driver: "bridge"
        name: artemis
volumes:
    artemis-postgresql-data:
        name: artemis-postgresql-data
