apiVersion: v1
data:
  EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: http://admin:$${jhipster.registry.password}@jhipster-registry:8761/eureka
  JHIPSTER_SLEEP: "30"
  MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED: "true"
  SPRING_CLOUD_CONFIG_URI: http://admin:$${jhipster.registry.password}@jhipster-registry:8761/config
  SPRING_PROFILES_ACTIVE: prod,api-docs
  _JAVA_OPTIONS: -Xmx512m -Xms256m
kind: ConfigMap
metadata:
  name: gateway
