apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: deployment-artemis-gateway
  name: gateway
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
        app: deployment-artemis-gateway
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
          app: deployment-artemis-gateway
    spec:
      containers:
      - env:
        - name: jhipster.registry.password
          valueFrom:
            secretKeyRef:
              key: jhipster.registry.password
              name: artemis-secrets
        envFrom:
        - configMapRef:
            name: gateway
            optional: false
        - configMapRef:
            name: jhipster-registry-config
            optional: false
        image: ghcr.io/ls1intum/artemis-gateway
        imagePullPolicy: Always
        name: gateway
        ports:
        - containerPort: 8089
          name: 8089tcp2
          protocol: TCP
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          privileged: false
          readOnlyRootFilesystem: false
          runAsNonRoot: false
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
