# This configuration is intended for development purpose, it's **your** responsibility to harden it for production
version: '3.8'
services:
    lecture-app:
        image: lecture
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,api-docs,artemis
            - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
            - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/eureka
            - SPRING_CLOUD_CONFIG_URI=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/config
            - SPRING_DATASOURCE_URL=jdbc:mysql://lecture-mysql:3306/lecture?useUnicode=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC&createDatabaseIfNotExist=true
            - SPRING_LIQUIBASE_URL=jdbc:mysql://lecture-mysql:3306/lecture?useUnicode=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC&createDatabaseIfNotExist=true
            - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
        depends_on:
            - artemis-mysql
    artemis-mysql:
        image: mysql:8.0.25
        # volumes:
        #   - ~/volumes/jhipster/lecture/mysql/:/var/lib/mysql/
        environment:
            - MYSQL_ALLOW_EMPTY_PASSWORD=yes
            - MYSQL_DATABASE=lecture
            - MYSQL_DATABASE=Artemis
        # If you want to expose these ports outside your dev PC, remove the "127.0.0.1:" prefix
        ports:
            - 127.0.0.1:3306:3306
        command: mysqld --lower_case_table_names=1 --skip-ssl --character_set_server=utf8mb4 --explicit_defaults_for_timestamp
    jhipster-registry:
        image: jhipster/jhipster-registry:v6.8.0
        volumes:
            - ./central-server-config:/central-config
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=dev,api-docs
            - SPRING_SECURITY_USER_PASSWORD=admin
            - JHIPSTER_REGISTRY_PASSWORD=admin
            - SPRING_CLOUD_CONFIG_SERVER_COMPOSITE_0_TYPE=native
            - SPRING_CLOUD_CONFIG_SERVER_COMPOSITE_0_SEARCH_LOCATIONS=file:./central-config/
        # If you want to expose these ports outside your dev PC, remove the "127.0.0.1:" prefix
        ports:
            - 127.0.0.1:8761:8761
