apiVersion: v1
kind: Secret
metadata:
  name: artemis-secrets
type: Opaque
data:
  artemis.athena.secret: ""
  artemis.continuous-integration.password: ""
  artemis.continuous-integration.token: ""
  artemis.lti.oauth-key: ""
  artemis.user-management.internal-admin.password: "YXJ0ZW1pc19hZG1pbg==" # base64 encoded "artemis_admin"
  artemis.user-management.ldap.password: ""
  artemis.version-control.password: ""
  artemis.version-control.token: ""
