apiVersion: v1
kind: Secret
metadata:
  name: artemis-secrets
type: Opaque
data:
  artemis.athene.base64-secret: ""
  artemis.continuous-integration.password: ""
  artemis.continuous-integration.token: ""
  artemis.lti.oauth-key: ""
  artemis.lti.oauth-secret: ""
  artemis.user-management.external.password: "YWRtaW4=" # base64 encoded "admin"
  artemis.user-management.internal-admin.password: "YXJ0ZW1pc19hZG1pbg==" # base64 encoded "artemis_admin"
  artemis.user-management.ldap.password: ""
  artemis.version-control.password: ""
  artemis.version-control.token: ""
  jhipster.registry.password: "YWRtaW4=" # base64 encoded "admin"
  spring.artemis.password: "Z3Vlc3Q=" # base64 encoded "guest"
