name: Build & Deploy Microservices

on:
  pull_request:
    paths-ignore:
    - 'README.md'
    - 'CODE_OF_CONDUCT.md'
    - 'CONTRIBUTING.md'
    - 'LICENSE'
    - 'SECURITY.md'
    - 'docs/**'
    - '.github/**'
    - '!.github/workflows/build-deploy-microservices.yml'
  push:
    branches:
    - develop
    - main
    - release/*
    tags: '[0-9]+.[0-9]+.[0-9]+'
    paths-ignore:
    - 'README.md'
    - 'CODE_OF_CONDUCT.md'
    - 'CONTRIBUTING.md'
    - 'LICENSE'
    - 'SECURITY.md'
    - 'docs/**'
    - '.github/**'
    - '!.github/workflows/build-deploy-microservices.yml'
  release:
    types:
    - created

# Keep in sync with codeql-analysis.yml and test.yml
env:
  CI: true
  node: 16.x
  java: 17
  RAW_URL: https://raw.githubusercontent.com/${{ github.repository }}/${{ github.sha }}

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Node.js
      uses: actions/setup-node@v2.4.1
      with:
        node-version: '${{ env.node }}'
        cache: 'npm'
    - name: Setup Java
      uses: actions/setup-java@v2.3.1
      with:
        distribution: 'zulu'
        java-version: '${{ env.java }}'
        cache: 'gradle'
    - name: Production Build Artemis
      run: ./gradlew -Pprod -Pwar clean bootWar -x webapp
      env:
        NODE_OPTIONS: --max_old_space_size=6144
    - name: Production Build Gateway
      run: ./gradlew -Pprod -Pwar :gateway:clean :gateway:bootWar
      env:
        NODE_OPTIONS: --max_old_space_size=6144
    - name: Production Build User Management Microservice
      run: ./gradlew -Pprod -Pwar :user-management:clean :user-management:bootWar
    - name: Production Build Lecture Microservice
      run: ./gradlew -Pprod -Pwar :lecture:clean :lecture:bootWar
    - name: Upload Artemis Artifact
      uses: actions/upload-artifact@v2
      with:
        name: Artemis.war
        path: build/libs/Artemis-*.war
    - name: Upload Gateway Artifact
      uses: actions/upload-artifact@v2
      with:
        name: gateway.war
        path: gateway/build/libs/gateway-*.war
    - name: Upload User Management Microservice Artifact
      uses: actions/upload-artifact@v2
      with:
        name: user-management.war
        path: user-management/build/libs/user-management-*.war
    - name: Upload Lecture Microservice Artifact
      uses: actions/upload-artifact@v2
      with:
        name: lecture.war
        path: lecture/build/libs/lecture-*.war
#    - name: Upload Release Artifact
#      if: github.event_name == 'release' && github.event.action == 'created'
#      uses: actions/upload-release-asset@v1
#      env:
#        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#      with:
#        upload_url: ${{ github.event.release.upload_url }}
#        asset_path: build/libs/Artemis-${{ github.event.release.tag_name }}.war
#        asset_name: Artemis.war
#        asset_content_type: application/x-webarchive

  docker_push_images:
    needs: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
        - image_name: "artemis-service"
          dockerfile_path: "src/main/docker"
          war_name: "Artemis.war"
        - image_name: "artemis-gateway"
          dockerfile_path: "gateway/src/main/docker"
          war_name: "gateway.war"
        - image_name: "artemis-usermanagement-service"
          dockerfile_path: "user-management/src/main/docker"
          war_name: "user-management.war"
        - image_name: "artemis-lecture-service"
          dockerfile_path: "lecture/src/main/docker"
          war_name: "lecture.war"
    steps:
    - name: Download Artifact
      uses: actions/download-artifact@v2
      with:
        name: ${{ matrix.war_name }}
    - name: Copy Dockerfile to Build Directory
      run: cp ${{ matrix.dockerfile_path }}/Dockerfile .
    - name: Build Docker Image
      run: docker build --build-arg WAR_PATH=. -t ${{ matrix.image_name }} .

    - name: Compute Tag
      uses: actions/github-script@v5
      id: compute-tag
      with:
        result-encoding: string
        script: |
          if (context.eventName === "pull_request") {
            return "pr-" + context.issue.number;
          }
          if (context.eventName === "push") {
            if (context.ref.startsWith("refs/tags/")) {
              return context.ref.slice(10);
            }
            if (context.ref === "refs/heads/develop") {
              return "latest";
            }
          }
          return "FALSE";

    # Push to GitHub Container Registry
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
      if: ${{ steps.compute-tag.outputs.result != 'FALSE' }}
    - name: Push to GitHub Container Registry
      env:
        TAG: ${{ steps.compute-tag.outputs.result }}
      run: |
        docker tag ${{ matrix.image_name }} ghcr.io/ls1intum/${{ matrix.image_name }}:$TAG
        docker push ghcr.io/ls1intum/${{ matrix.image_name }}:$TAG
      if: ${{ steps.compute-tag.outputs.result != 'FALSE' }}

    # TODO: Push to Docker Hub (develop + tag)

    # TODO: Push to Chair Habour (??)
    #
  deploy:
    needs: docker_push_images
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - environment: artemistest6
            url: https://artemistest6.ase.in.tum.de
    environment:
      url: ${{ matrix.url }}
      name: ${{ matrix.environment }}
    steps:
    - name: Compute Tag
      uses: actions/github-script@v5
      id: compute-tag
      with:
        result-encoding: string
        script: |
          if (context.eventName === "pull_request") {
            return "pr-" + context.issue.number;
          }
          if (context.eventName === "push") {
            if (context.ref.startsWith("refs/tags/")) {
              return context.ref.slice(10);
            }
            if (context.ref === "refs/heads/develop") {
              return "latest";
            }
          }
          return "FALSE";

    - name: Check "lock:${{ matrix.environment }}" label
      uses: actions/github-script@v5
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const opts = github.rest.issues.listForRepo.endpoint.merge({
            owner: context.repo.owner,
            repo: context.repo.repo,
            labels: ['lock:${{ matrix.environment }}']
          })
          const issues = await github.paginate(opts)
          if (issues.length == 1 && (!context.issue || issues[0].number != context.issue.number)) {
            core.setFailed(`Testserver "${{ matrix.environment }}" is already in use by PR #${issues[0].number}.`);
          } else if (issues.length > 1) {
            core.setFailed('Testserver "${{ matrix.environment }}" is already in use by multiple PRs. Check PRs with label "lock:${{ matrix.environment }}"!');
          } else if (context.issue && context.issue.number) {
            await github.rest.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ['lock:${{ matrix.environment }}']
            })
          }

    - name: Install OpenVPN
      run: sudo apt-get --assume-yes --no-install-recommends install openvpn

    # Fill config from Secret (https://tum.eduvpn.lrz.de/vpn-user-portal/configurations)
    - name: Configure LRZ eduVPN
      run: echo "${{ secrets.LRZ_OVPN_CONFIG }}" > lrz.ovpn
    - name: Connect VPN
      run: sudo openvpn --config "lrz.ovpn" --log "vpn.log" --daemon
    - name: Wait for a VPN connection. Ping nas.ads.mwn.de (only accessible inside MWN)
      run: until ping -c1 nas.ads.mwn.de; do sleep 2; done
      timeout-minutes: 2

    # Configure SSH Key
    - name: Setup SSH Keys and known_hosts
      env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
          DEPLOYMENT_HOSTS: "${{ secrets.DEPLOYMENT_HOSTS }}"
          SSH_PRIVATE_KEY: "${{ secrets.SSH_PRIVATE_KEY }}"
      run: |
          mkdir -p ~/.ssh
          for host in $DEPLOYMENT_HOSTS; do
            ssh-keyscan $host >> ~/.ssh/known_hosts
          done
          ssh-agent -a $SSH_AUTH_SOCK > /dev/null
          ssh-add - <<< $SSH_PRIVATE_KEY

    - name: Deploy Docker Compose Files
      env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
          DEPLOYMENT_HOSTS: "${{ secrets.DEPLOYMENT_HOSTS }}"
          DEPLOYMENT_USER: ${{ secrets.DEPLOYMENT_USER }}
      run: |
        for host in $DEPLOYMENT_HOSTS; do
          # Copy docker-compose files to remote host
          scp docker-compose-microservices* $DEPLOYMENT_USER@$host:/opt/artemis/

          # Pull and Start images
          ssh -t $DEPLOYMENT_USER@$host "
            cd /opt/artemis &&
            echo TAG=${{ steps.compute-tag.outputs.result }} > .env &&
            docker-compose -f docker-compose-microservices.yml -f docker-compose-microservices.override-prod.yml down &&
            docker-compose -f docker-compose-microservices.yml -f docker-compose-microservices.override-prod.yml pull &&
            docker-compose -f docker-compose-microservices.yml -f docker-compose-microservices.override-prod.yml up -d"

          sleep 20
        done

    # Always disconnect from VPN
    - name: Disconncet VPN
      run: |
        sudo killall openvpn
        rm lrz.ovpn
      if: always()
