name: Pull Request Converted to draft
on:
  pull_request_target:
    types: [assigned, unassigned, labeled, unlabeled, opened, edited, closed, reopened, synchronize, locked, unlocked]

jobs:
  moveToInProgress:
    runs-on: ubuntu-latest
    steps:
      - name: Move to "In progress" column
        if: github.event.pull_request.draft == true
        uses: alex-page/github-project-automation-plus@v0.8.2
        with:
          project: Artemis Development
          column: In progress
          repo-token: ${{ secrets.GH_TOKEN_ADD_TO_PROJECT }}
