name: Pull Request Opened
on:
  pull_request_target:
    types: [opened]

jobs:
  assign:
    runs-on: ubuntu-latest
    steps:
      - name: Assign Pull Request to its Author
        uses: technote-space/assign-author@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  addToProject:
    runs-on: ubuntu-latest
    steps:
      - name: Add Pull Request to Project
        uses: alex-page/github-project-automation-plus@v0.8.2
        with:
          project: Artemis Development
          column: In progress
          repo-token: ${{ secrets.GH_TOKEN_ADD_TO_PROJECT }}
