name: Pull Request Ready for Review
on:
  pull_request_target:
    types: [ready_for_review]

jobs:
  pullequestReadyForReview:
    runs-on: ubuntu-latest
    steps:

      - name: Move to "Ready for review" column
        if: github.event.pull_request.draft == false
        uses: alex-page/github-project-automation-plus@v0.8.3
        with:
          project: Artemis Development
          column: Ready for review
          repo-token: ${{ secrets.GH_TOKEN_ADD_TO_PROJECT }}

      - name: Label "ready for review"
        uses: actions/github-script@v7
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            await github.rest.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ['ready for review']
            })
