name: Stale
on:
  schedule:
    - cron: "0 * * * *"

jobs:
  stale:
    if: github.repository_owner == 'ls1intum'
    runs-on: ubuntu-latest
    steps:
      - name: Check for stale PRs
        uses: actions/stale@v5
        with:
          days-before-stale: 7
          days-before-close: 14
          # Disable issue checking, only PR
          days-before-issue-stale: -1
          remove-stale-when-updated: true
          stale-pr-label: "stale"
          exempt-pr-labels: "no-stale"
          stale-pr-message: >
            There hasn't been any activity on this pull request recently. 
            Therefore, this pull request has been automatically marked as stale
            and will be closed if no further activity occurs within **seven** days.
            Thank you for your contributions.
