name: Pull Request Opened
on:
  pull_request_target:
    types: [opened]

jobs:
  assign:
    runs-on: ubuntu-latest
    steps:
      - name: Assign Pull Request to its Author
        uses: technote-space/assign-author@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  addToProject:
    runs-on: ubuntu-latest
    steps:
      - name: Add Pull Request to Project
        uses: alex-page/github-project-automation-plus@v0.8.0
        with:
          project: Artemis Development
          column: In progress
          repo-token: ${{ secrets.GH_TOKEN_ADD_TO_PROJECT }}

  commentOnNonDraft:
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false && !contains(github.event.issue.labels.*.name, 'ready for review') && github.event.pull_request.user.login != 'dependabot[bot]'
    steps:
      - name: Comment PR
        uses: thollander/actions-comment-pull-request@master
        with:
          message: 'Still in progress? Consider converting to draft.'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
